### ISSUE TITLE
Links broken?

### ISSUE THREAD

**Issue by pstoehr** [EEXCESS/eexcess#6] opened 2015-09-28 08:23 UTC
Hi EEXCESS-Team, 

the links to JSON-documentation found at https://github.com/EEXCESS/eexcess/wiki/The-Privacy-Proxy-Services seems to be broken.

Best regards
    Peter Stöhr
![links](https://cloud.githubusercontent.com/assets/14542721/10130703/ef6b1af0-65ca-11e5-84b1-64e9d94b5656.png)

**Comment by chseifert** [comment] 2015-09-28 08:32
Not sure, who is responsible for the PP docu, Johannes, if it is Albin or Thomas, feel free to reassign ;-)

**Comment by ThomasCerq** [comment] 2015-09-28 08:33
I'm on it right now. The problem is that some changes the title of the page. Therefore the URL is modified to. It will be fixed in a couple of minutes.

**Comment by ThomasCerq** [comment] 2015-09-28 08:40
Fixed.

**Closed as completed by ThomasCerq** 2015-09-28 08:40 UTC
